<a href="https://colab.research.google.com/github/milu234/DataScience_AI/blob/master/Data_Science'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Automatic array generation

In [2]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

For identity matrix in linear algebra

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.random.rand(5)

array([0.87176966, 0.12638244, 0.80235941, 0.39172155, 0.79831061])

In [8]:
np.random.randn(5)

array([-0.16768771, -1.65697715, -0.61672795, -0.00299035, -1.72085199])

In [9]:
arr = np.random.randint(0,10,10)

In [10]:
arr

array([2, 7, 4, 3, 8, 5, 9, 1, 3, 2])

In [11]:
arr = arr.reshape(5,2)

In [12]:
arr.argmax()

6

In [13]:
arr.argmin()

7

In [14]:
arr.shape

(5, 2)

Numpy Indexing and selection


In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[8]

8

In [18]:
arr[1:5]

array([1, 2, 3, 4])

In [19]:
arr[0:4]

array([0, 1, 2, 3])

In [20]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[0:5] = 100

In [24]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
x = arr[1:5]
x

array([1, 2, 3, 4])

In [28]:
x[:] = 99

In [29]:
x,arr

(array([99, 99, 99, 99]), array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10]))

In [30]:
arr_2d = np.array([[6,7,8],[25,78,98],[89,67,24]])

In [31]:
arr_2d

array([[ 6,  7,  8],
       [25, 78, 98],
       [89, 67, 24]])

In [32]:
arr_2d[2][2]

24

In [33]:
arr_2d[2,2]

24

In [34]:
arr_2d[1:,:2]

array([[25, 78],
       [89, 67]])

In [35]:

arr = np.arange(2,10)

In [36]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
bool_arr = arr > 5

In [38]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True])

In [39]:
arr[bool_arr]

array([6, 7, 8, 9])