<a href="https://colab.research.google.com/github/milu234/DataScience_AI/blob/master/Data_Science'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
import pandas as pd

Automatic array generation

In [58]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [59]:
np.zeros(3)

array([0., 0., 0.])

In [60]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

For identity matrix in linear algebra

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.random.rand(5)

array([0.19234481, 0.00092567, 0.74461159, 0.24822652, 0.57128967])

In [64]:
np.random.randn(5)

array([-0.41355653, -1.81783741,  2.87708014,  0.00653448,  0.65952559])

In [65]:
arr = np.random.randint(0,10,10)

In [66]:
arr

array([1, 1, 5, 1, 9, 6, 9, 8, 9, 8])

In [67]:
arr = arr.reshape(5,2)

In [68]:
arr.argmax()

4

In [69]:
arr.argmin()

0

In [70]:
arr.shape

(5, 2)

Numpy Indexing and selection


In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr[8]

8

In [74]:
arr[1:5]

array([1, 2, 3, 4])

In [75]:
arr[0:4]

array([0, 1, 2, 3])

In [76]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[0:5] = 100

In [80]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [81]:
arr = np.arange(0,11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
x = arr[1:5]
x

array([1, 2, 3, 4])

In [84]:
x[:] = 99

In [85]:
x,arr

(array([99, 99, 99, 99]), array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10]))

In [86]:
arr_2d = np.array([[6,7,8],[25,78,98],[89,67,24]])

In [87]:
arr_2d

array([[ 6,  7,  8],
       [25, 78, 98],
       [89, 67, 24]])

In [88]:
arr_2d[2][2]

24

In [89]:
arr_2d[2,2]

24

In [90]:
arr_2d[1:,:2]

array([[25, 78],
       [89, 67]])

In [91]:

arr = np.arange(2,10)

In [92]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
bool_arr = arr > 5

In [94]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True])

In [95]:
arr[bool_arr]

array([6, 7, 8, 9])

In [96]:
arr_2d = np.arange(50).reshape(5,10)

In [97]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [98]:
arr_2d[2:4,2:4]

array([[22, 23],
       [32, 33]])

Numpy operations

In [99]:
arr_op = np.arange(0,11)

In [100]:
arr_op

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr_op / arr_op

<ipython-input-101-6bcc9ffefc07>:1: RuntimeWarning: invalid value encountered in true_divide
  arr_op / arr_op


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [102]:
arr_op * arr_op

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Pandas

In [103]:
import pandas as pd


In [104]:
labels  = ['a', 'b', 'c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a' : 10, 'b' : 20, 'c': 30}

In [105]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [106]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [107]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [108]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','JAPAN'])

In [109]:
ser1

USA        1
Germany    2
USSR       3
JAPAN      4
dtype: int64

In [110]:
ser3 = pd.Series(data = labels)

In [111]:
ser3

0    a
1    b
2    c
dtype: object

In [116]:
df = pd.DataFrame(np.random.randn(5,4),['P', 'Q', 'R', 'S', 'T'],['A','B','C','D'])

In [117]:
df

A         B         C         D
P -0.793418  0.037466  0.426412  1.018478
Q -0.981284  2.265696  0.928453  1.616432
R -1.187474  1.137774 -1.125867  0.845568
S -1.229038 -0.825273 -0.310759  0.389880
T  0.344408 -1.764044  0.751701  1.506167