<a href="https://colab.research.google.com/github/milu234/DataScience_AI/blob/master/Data_Science'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

Automatic array generation

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

For identity matrix in linear algebra

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.00770573, 0.02357868, 0.21790693, 0.68403657, 0.14098761])

In [17]:
np.random.randn(5)

array([-0.11117477, -0.02741306,  0.26644984,  0.52995972,  1.26737391])

In [18]:
arr = np.random.randint(0,10,10)

In [19]:
arr

array([0, 7, 0, 4, 6, 7, 5, 1, 1, 4])

In [20]:
arr = arr.reshape(5,2)

In [21]:
arr.argmax()

1

In [22]:
arr.argmin()

0

In [23]:
arr.shape

(5, 2)

Numpy Indexing and selection


In [24]:
arr = np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[8]

8

In [27]:
arr[1:5]

array([1, 2, 3, 4])

In [28]:
arr[0:4]

array([0, 1, 2, 3])

In [29]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[0:5] = 100

In [34]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = arr[1:5]
x

array([1, 2, 3, 4])

In [38]:
x[:] = 99

In [39]:
x,arr

(array([99, 99, 99, 99]), array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10]))

In [40]:
arr_2d = np.array([[6,7,8],[25,78,98],[89,67,24]])

In [41]:
arr_2d

array([[ 6,  7,  8],
       [25, 78, 98],
       [89, 67, 24]])

In [42]:
arr_2d[2][2]

24