<a href="https://colab.research.google.com/github/milu234/DataScience_AI/blob/master/Data_Science'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

Automatic array generation

In [2]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

For identity matrix in linear algebra

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.random.rand(5)

array([0.32228855, 0.4530164 , 0.60025517, 0.12019243, 0.37130357])

In [8]:
np.random.randn(5)

array([ 1.06377467, -0.69221068,  0.10139202, -1.53840441, -0.7658015 ])

In [9]:
arr = np.random.randint(0,10,10)

In [10]:
arr

array([5, 4, 8, 8, 8, 2, 4, 4, 7, 4])

In [11]:
arr = arr.reshape(5,2)

In [12]:
arr.argmax()

2

In [13]:
arr.argmin()

5

In [14]:
arr.shape

(5, 2)

Numpy Indexing and selection


In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[8]

8

In [18]:
arr[1:5]

array([1, 2, 3, 4])

In [19]:
arr[0:4]

array([0, 1, 2, 3])

In [20]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr[0:5] = 100

In [24]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr = np.arange(0,11)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
x = arr[1:5]
x

array([1, 2, 3, 4])

In [28]:
x[:] = 99

In [29]:
x,arr

(array([99, 99, 99, 99]), array([ 0, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10]))

In [30]:
arr_2d = np.array([[6,7,8],[25,78,98],[89,67,24]])

In [31]:
arr_2d

array([[ 6,  7,  8],
       [25, 78, 98],
       [89, 67, 24]])

In [32]:
arr_2d[2][2]

24

In [33]:
arr_2d[2,2]

24

In [34]:
arr_2d[1:,:2]

array([[25, 78],
       [89, 67]])

In [35]:

arr = np.arange(2,10)

In [36]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
bool_arr = arr > 5

In [38]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True])

In [39]:
arr[bool_arr]

array([6, 7, 8, 9])

In [40]:
arr_2d = np.arange(50).reshape(5,10)

In [41]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr_2d[2:4,2:4]

array([[22, 23],
       [32, 33]])

Numpy operations

In [43]:
arr_op = np.arange(0,11)

In [44]:
arr_op

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr_op / arr_op

<ipython-input-45-6bcc9ffefc07>:1: RuntimeWarning: invalid value encountered in true_divide
  arr_op / arr_op


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [46]:
arr_op * arr_op

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Pandas

In [47]:
import pandas as pd


In [48]:
labels  = ['a', 'b', 'c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a' : 10, 'b' : 20, 'c': 30}

In [49]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [50]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [51]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [52]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','JAPAN'])

In [53]:
ser1

USA        1
Germany    2
USSR       3
JAPAN      4
dtype: int64

In [54]:
ser3 = pd.Series(data = labels)

In [55]:
ser3

0    a
1    b
2    c
dtype: object

In [56]:
df = pd.DataFrame(np.random.randn(5,4),['P', 'Q', 'R', 'S', 'T'],['A','B','C','D'])

In [57]:
df

A         B         C         D
P -1.188478  1.272983  2.172488  2.245085
Q  0.235701  1.985180  0.766303 -1.067528
R -0.533356  1.373169 -2.019787  1.757025
S -0.544521  0.976185  0.636993  0.210229
T -0.590598  0.344240 -0.271995 -1.137264

In [58]:
df[df['C']>0]

A         B         C         D
P -1.188478  1.272983  2.172488  2.245085
Q  0.235701  1.985180  0.766303 -1.067528
S -0.544521  0.976185  0.636993  0.210229

In [59]:
df[df['C']>0].loc['P']

A   -1.188478
B    1.272983
C    2.172488
D    2.245085
Name: P, dtype: float64

In [60]:
df

A         B         C         D
P -1.188478  1.272983  2.172488  2.245085
Q  0.235701  1.985180  0.766303 -1.067528
R -0.533356  1.373169 -2.019787  1.757025
S -0.544521  0.976185  0.636993  0.210229
T -0.590598  0.344240 -0.271995 -1.137264

In [61]:
df[(df['A']>0) & (df['B']<2)]

A        B         C         D
Q  0.235701  1.98518  0.766303 -1.067528

In [62]:
data = {
    'Company' : ['TCS','TCS','Wipro','Wipro','Infosys','Infosys'],
    'Name':['Sam','Nam','Jam','Cam','Pam','Ram'],
    'Sales':[1200, 300, 700, 800, 600, 800]
}

In [63]:
df = pd.DataFrame(data)

In [64]:
df

Company Name  Sales
0      TCS  Sam   1200
1      TCS  Nam    300
2    Wipro  Jam    700
3    Wipro  Cam    800
4  Infosys  Pam    600
5  Infosys  Ram    800

In [65]:
df.groupby('Company')

In [66]:
byComp = df.groupby('Company')

In [67]:
byComp.mean()

Sales
Company       
Infosys  700.0
TCS      750.0
Wipro    750.0

In [68]:
  byComp.sum()

Sales
Company       
Infosys   1400
TCS       1500
Wipro     1500

In [69]:
byComp.std()

Sales
Company            
Infosys  141.421356
TCS      636.396103
Wipro     70.710678

In [70]:
byComp.describe()

Sales                                                       
        count   mean         std    min    25%    50%    75%     max
Company                                                             
Infosys   2.0  700.0  141.421356  600.0  650.0  700.0  750.0   800.0
TCS       2.0  750.0  636.396103  300.0  525.0  750.0  975.0  1200.0
Wipro     2.0  750.0   70.710678  700.0  725.0  750.0  775.0   800.0

Merging, concting etc with DataFrame

In [78]:
data1 = {'key' : ['K1','K2','K3','K4','K5'],
        'A':[ 78, 89, 9, 98, 65],
        'B':[12,34,56,67,89]}

In [79]:
data2 = {'key' : ['K1','K2','K3','K4','K5'],
        'C':[ 78, 89, 9, 98, 65],
        'D':[12,34,56,67,89]}

In [81]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [82]:
df3 = pd.merge(df1, df2, how='inner', on = 'key')

In [83]:
df3

key   A   B   C   D
0  K1  78  12  78  12
1  K2  89  34  89  34
2  K3   9  56   9  56
3  K4  98  67  98  67
4  K5  65  89  65  89